### ISSUE TITLE
memory question

### ISSUE THREAD

**Issue by dz12123** [human-analysis/AutoFHE#1]
Hello, I am very interested in your research, but my experimental equipment does not have as much memory as yours, and there will be a killed error when running the program, please ask what parameters should be modified to run the program under the guarantee of safety, thank you

**Comment by Wei-Ao** [comment]
Hi, thanks for your interest in our work. Bootstrapping keys use a lot of memory. Maybe you can try to evaluate only one image per run, I assume ~300G is enough for one image.

**Comment by dz12123** [comment]
Thank you for your reply, my device has about 200GB of available memory, I see that this implementation is built on top of mpcnn, and it is not a hard requirement to mention memory in mpcnn, how should I solve the problem of insufficient memory
![image](https://github.com/user-attachments/assets/c86944d4-1021-4efe-bf1a-7bff7413307b)

**Comment by Wei-Ao** [comment]
Hi, our memory requirement is the same as MPCNN. The setup is the same. We do not have a simple way to reduce the memory footprint.

**Comment by dz12123** [comment]
Thank you very much for your reply, I'm thinking about other options
